/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_u17webplib_webplib */

#ifndef _Included_com_u17webplib_webplib
#define _Included_com_u17webplib_webplib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_u17webplib_webplib
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_u17webplib_webplib_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_u17webplib_webplib
 * Method:    getWebPDecodeRGB
 * Signature: ([BJ[I[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_u17webplib_webplib_getWebPDecodeRGB
  (JNIEnv *, jclass, jbyteArray, jlong, jintArray, jintArray);

/*
 * Class:     com_u17webplib_webplib
 * Method:    getAdvancedDecode
 * Signature: ([BII[I[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_u17webplib_webplib_getAdvancedDecode
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
